name: publish

on:
  push:
    # branches:
    #   - main

jobs:
  build:
    runs-on: ubuntu-latest

    container: tuemura00/texlive

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site

  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: _site
          jekyll: false
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
